# Managed by https://github.com/powerhome/software. Do not make changes here, they will be reverted.
creation_rules:
  - path_regex: production
    key_groups:
      - kms:
          - arn: "arn:aws:kms:us-east-1:205083374951:key/e9dd6f18-7ce0-481b-925f-40c2c3bf89fb"
          - arn: "arn:aws:kms:us-east-1:205083374951:key/e9dd6f18-7ce0-481b-925f-40c2c3bf89fb"
            role: "arn:aws:iam::205083374951:role/watchtower"

  - key_groups:
      - kms:
          - arn: "arn:aws:kms:us-east-1:205083374951:key/b74101d5-abe1-49fe-95a7-acf8da9bb5f8"
          - arn: "arn:aws:kms:us-east-1:205083374951:key/b74101d5-abe1-49fe-95a7-acf8da9bb5f8"
            role: "arn:aws:iam::205083374951:role/watchtower"
