FROM gcr.io/distroless/static:nonroot@sha256:627d6c5a23ad24e6bdff827f16c7b60e0289029b0c79e9f7ccd54ae3279fb45f

# Copy the pre-built binary from the controller build
COPY manager /manager

# Use nonroot user for security
USER 65532:65532

ENTRYPOINT ["/manager"]
