resources:
- manager.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
patchesStrategicMerge:
- kind-imagepullpolicy-patch.yaml
images:
- name: controller
  newName: powerhome/pac-quota-controller
  newTag: latest
