{{- if .Values.rbac.enable }}
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    {{- include "chart.labels" . | nindent 4 }}
  {{- with .Values.controllerManager.serviceAccount }}
    {{- if .annotations }}
  annotations:
      {{- range $key, $value := .annotations }}
    {{ $key }}: {{ $value }}
      {{- end }}
    {{- end }}
  {{- end }}
  name: {{ .Values.controllerManager.serviceAccount.name | default "pac-quota-controller-manager" }}
  namespace: {{ .Release.Namespace }}
{{- end -}}
