apiVersion: apps/v1
kind: Deployment
metadata:
  name: pac-quota-controller-manager
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "chart.labels" . | nindent 4 }}
    control-plane: controller-manager
spec:
  replicas:  {{ .Values.controllerManager.replicas }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 0
  selector:
    matchLabels:
      {{- include "chart.selectorLabels" . | nindent 6 }}
      control-plane: controller-manager
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/default-container: manager
      labels:
        {{- include "chart.labels" . | nindent 8 }}
        control-plane: controller-manager
        {{- with .Values.controllerManager.pod }}
        {{- with .labels }}
        {{- range $key, $value := . }}
        {{ $key }}: {{ $value }}
        {{- end }}
        {{- end }}
        {{- end }}
    spec:
      {{- if .Values.controllerManager.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml .Values.controllerManager.imagePullSecrets | nindent 8 }}
      {{- end }}
      containers:
        - name: manager
          args:
            {{- range .Values.controllerManager.container.args }}
            - {{ . }}
            {{- end }}
            {{- if .Values.controllerManager.excludeNamespaceLabelKey }}
            - --exclude-namespace-label-key={{ .Values.controllerManager.excludeNamespaceLabelKey }}
            {{- end }}
            {{- if .Values.webhook.dryRunOnly }}
            - --webhook-dry-run-only=true
            {{- end }}
            - --webhook-cert-path={{ .Values.controllerManager.container.webhookCertPath }}
          ports:
          - containerPort: 9443
            name: webhook-server
            protocol: TCP
          {{- if .Values.metrics.enable }}
          - containerPort: 8443
            name: metrics-server
            protocol: TCP
          {{- end }}
          command:
            - /manager
          image: {{ .Values.controllerManager.container.image.repository }}:{{ .Values.controllerManager.container.image.tag }}
          imagePullPolicy: {{ .Values.controllerManager.container.image.pullPolicy | default "IfNotPresent" }}
          env:
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          {{- if .Values.controllerManager.container.env }}
            {{- range $key, $value := .Values.controllerManager.container.env }}
            - name: {{ $key }}
              value: {{ $value }}
            {{- end }}
          {{- end }}
          livenessProbe:
            {{- toYaml .Values.controllerManager.container.livenessProbe | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.controllerManager.container.readinessProbe | nindent 12 }}
          resources:
            {{- toYaml .Values.controllerManager.container.resources | nindent 12 }}
          securityContext:
            {{- toYaml .Values.controllerManager.container.securityContext | nindent 12 }}
          volumeMounts:
            {{- if .Values.metrics.enable }}
            - name: metrics-certs
              mountPath: /tmp/k8s-metrics-server/metrics-certs
              readOnly: true
            {{- end }}
            {{- if .Values.webhook.enable }}
            - name: webhook-certs
              mountPath: {{ .Values.controllerManager.container.webhookCertPath | default "/tmp/k8s-webhook-server/serving-certs" }}
              readOnly: true
            {{- end }}
      securityContext:
        {{- toYaml .Values.controllerManager.securityContext | nindent 8 }}
      serviceAccountName: {{ .Values.controllerManager.serviceAccount.name }}
      terminationGracePeriodSeconds: {{ .Values.controllerManager.terminationGracePeriodSeconds }}
      volumes:
        {{- if .Values.metrics.enable }}
        {{- if .Values.certmanager.enable }}
        - name: metrics-certs
          secret:
            secretName: metrics-server-cert # Default secret name for cert-manager managed metrics certs
        {{- else if .Values.metrics.customTLS.secretName }}
        - name: metrics-certs
          secret:
            secretName: {{ .Values.metrics.customTLS.secretName }}
        {{- end }}
        {{- end }}
        {{- if .Values.webhook.enable }}
        {{- if .Values.certmanager.enable }}
        - name: webhook-certs
          secret:
            secretName: webhook-server-cert # Default secret name for cert-manager managed webhook certs
        {{- else if  .Values.webhook.customTLS.secretName }}
        - name: webhook-certs
          secret:
            secretName: {{ .Values.webhook.customTLS.secretName }}
        {{- end }}
        {{- end }}
