{{- if .Values.certManager.enabled -}}
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: {{ .Values.certManager.issuerName }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "pac-quota-controller.labels" . | nindent 4 }}
spec:
  selfSigned: {}
{{- end -}}
