apiVersion: v1
kind: Service
metadata:
  name: {{ include "pac-quota-controller.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "pac-quota-controller.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 443
      targetPort: webhook
      protocol: TCP
      name: webhook
  selector:
    {{- include "pac-quota-controller.selectorLabels" . | nindent 4 }}
