apiVersion: quota.powerapp.cloud/v1alpha1
kind: ClusterResourceQuota
metadata:
  labels:
    app.kubernetes.io/name: pac-quota-controller
    app.kubernetes.io/managed-by: kustomize
  name: clusterresourcequota-sample
spec:
  hard:
    pods: "10"
    requests.cpu: "1"
    requests.memory: 1Gi
    limits.cpu: "2"
    limits.memory: 2Gi
  namespaceSelector:
    matchLabels:
      quota: limited
  scopes:
  - NotTerminating
  scopeSelector:
    matchExpressions:
    - operator: In
      scopeName: PriorityClass
      values:
      - high
