---
apiVersion: v1
kind: Namespace
metadata:
  name: gpu-team
  labels:
    team: gpu-users
---
apiVersion: quota.powerapp.cloud/v1alpha1
kind: ClusterResourceQuota
metadata:
  name: gpu-quota
spec:
  namespaceSelector:
    matchLabels:
      team: gpu-users
  hard:
    requests.nvidia.com/gpu: "4"
    requests.cpu: "2"
    requests.memory: "4Gi"
---
apiVersion: v1
kind: Pod
metadata:
  name: gpu-workload
  namespace: gpu-team
spec:
  containers:
  - name: gpu-container
    image: nvidia/cuda:11.0-base
    resources:
      requests:
        nvidia.com/gpu: "2"
        cpu: "500m"
        memory: "1Gi"
      limits:
        cpu: "1"
        memory: "2Gi"
---
apiVersion: v1
kind: Pod
metadata:
  name: gpu-workload-with-init
  namespace: gpu-team
spec:
  initContainers:
  - name: init-setup
    image: busybox
    resources:
      requests:
        nvidia.com/gpu: "1"
        cpu: "100m"
        memory: "128Mi"
  containers:
  - name: main-gpu-container
    image: nvidia/cuda:11.0-base
    resources:
      requests:
        nvidia.com/gpu: "1"
        cpu: "400m"
        memory: "1Gi"
      limits:
        cpu: "800m"
        memory: "2Gi"
