{{- if .Values.webhook.enable }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: pac-quota-controller-manager-allow-webhook-traffic
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: pac-quota-controller
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: pac-quota-controller
      control-plane: controller-manager
  policyTypes:
    - Ingress
  ingress:
    - from:
        - namespaceSelector: {}
      ports:
        - protocol: TCP
          port: 9443
{{- end }}
