{{- if .Values.webhook.enable }}
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: pac-quota-controller-validating-webhook
  labels:
    app.kubernetes.io/name: pac-quota-controller
  annotations:
    {{- if .Values.certmanager.enable }}
    cert-manager.io/inject-ca-from: {{ .Release.Namespace }}/webhook-server-cert
    {{- end }}
webhooks:
  - name: vclusterresourcequota-v1alpha1.powerapp.cloud
    admissionReviewVersions: ["v1"]
    sideEffects: None
    failurePolicy: Fail
    timeoutSeconds: 30
    clientConfig:
      {{- if not .Values.certmanager.enable }}
      caBundle: {{ .Values.webhook.customTLS.caBundle }}
      {{- end }}
      service:
        name: pac-quota-controller-webhook-service
        namespace: {{ .Release.Namespace }}
        path: /validate-quota-powerapp-cloud-v1alpha1-clusterresourcequota
    rules:
      - apiGroups: ["quota.powerapp.cloud"]
        apiVersions: ["v1alpha1"]
        operations: ["CREATE", "UPDATE"]
        resources: ["clusterresourcequotas"]
    namespaceSelector:
      matchExpressions:
        - key: kubernetes.io/metadata.name
          operator: NotIn
          values:
          {{- range (include "pacQuota.excludedNamespacesList" . | splitList " ") }}
          - {{ . | quote }}
          {{- end }}
  - name: vnamespace-v1alpha1.powerapp.cloud
    admissionReviewVersions: ["v1"]
    sideEffects: None
    failurePolicy: Fail
    timeoutSeconds: 30
    clientConfig:
      {{- if not .Values.certmanager.enable }}
      caBundle: {{ .Values.webhook.customTLS.caBundle }}
      {{- end }}
      service:
        name: pac-quota-controller-webhook-service
        namespace: {{ .Release.Namespace }}
        path: /validate--v1-namespace
    rules:
      - apiGroups: [""]
        apiVersions: ["v1"]
        operations: ["CREATE", "UPDATE"]
        resources: ["namespaces"]
    namespaceSelector:
      matchExpressions:
        - key: kubernetes.io/metadata.name
          operator: NotIn
          values:
          {{- range (include "pacQuota.excludedNamespacesList" . | splitList " ") }}
          - {{ . | quote }}
          {{- end }}
  - name: vpod-v1alpha1.powerapp.cloud
    admissionReviewVersions: ["v1"]
    sideEffects: None
    failurePolicy: Fail
    timeoutSeconds: 30
    clientConfig:
      {{- if not .Values.certmanager.enable }}
      caBundle: {{ .Values.webhook.customTLS.caBundle }}
      {{- end }}
      service:
        name: pac-quota-controller-webhook-service
        namespace: {{ .Release.Namespace }}
        path: /validate--v1-pod
    rules:
      - apiGroups: [""]
        apiVersions: ["v1"]
        operations: ["CREATE", "UPDATE"]
        resources: ["pods"]
    namespaceSelector:
      matchExpressions:
        - key: kubernetes.io/metadata.name
          operator: NotIn
          values:
          {{- range (include "pacQuota.excludedNamespacesList" . | splitList " ") }}
          - {{ . | quote }}
          {{- end }}
  - name: vpersistentvolumeclaim-v1alpha1.powerapp.cloud
    admissionReviewVersions: ["v1"]
    sideEffects: None
    failurePolicy: Fail
    timeoutSeconds: 30
    clientConfig:
      {{- if not .Values.certmanager.enable }}
      caBundle: {{ .Values.webhook.customTLS.caBundle }}
      {{- end }}
      service:
        name: pac-quota-controller-webhook-service
        namespace: {{ .Release.Namespace }}
        path: /validate--v1-persistentvolumeclaim
    rules:
      - apiGroups: [""]
        apiVersions: ["v1"]
        operations: ["CREATE", "UPDATE"]
        resources: ["persistentvolumeclaims"]
    namespaceSelector:
      matchExpressions:
        - key: kubernetes.io/metadata.name
          operator: NotIn
          values:
          {{- range (include "pacQuota.excludedNamespacesList" . | splitList " ") }}
          - {{ . | quote }}
          {{- end }}
  - name: vservice-v1alpha1.powerapp.cloud
    admissionReviewVersions: ["v1"]
    sideEffects: None
    failurePolicy: Fail
    timeoutSeconds: 30
    clientConfig:
      {{- if not .Values.certmanager.enable }}
      caBundle: {{ .Values.webhook.customTLS.caBundle }}
      {{- end }}
      service:
        name: pac-quota-controller-webhook-service
        namespace: {{ .Release.Namespace }}
        path: /validate--v1-service
    rules:
      - apiGroups: [""]
        apiVersions: ["v1"]
        operations: ["CREATE", "UPDATE"]
        resources: ["services"]
    namespaceSelector:
      matchExpressions:
        - key: kubernetes.io/metadata.name
          operator: NotIn
          values:
          {{- range (include "pacQuota.excludedNamespacesList" . | splitList " ") }}
          - {{ . | quote }}
          {{- end }}
  - name: vobjectcount-v1alpha1.powerapp.cloud
    admissionReviewVersions: ["v1"]
    sideEffects: None
    failurePolicy: Fail
    timeoutSeconds: 30
    clientConfig:
      {{- if not .Values.certmanager.enable }}
      caBundle: {{ .Values.webhook.customTLS.caBundle }}
      {{- end }}
      service:
        name: pac-quota-controller-webhook-service
        namespace: {{ .Release.Namespace }}
        path: /validate-objectcount-v1
    rules:
      - apiGroups: [""]
        apiVersions: ["v1"]
        operations: ["CREATE", "UPDATE"]
        resources: ["configmaps", "secrets", "replicationcontrollers"]
      - apiGroups: ["apps"]
        apiVersions: ["v1"]
        operations: ["CREATE", "UPDATE"]
        resources: ["deployments", "statefulsets", "daemonsets"]
      - apiGroups: ["batch"]
        apiVersions: ["v1"]
        operations: ["CREATE", "UPDATE"]
        resources: ["jobs", "cronjobs"]
      - apiGroups: ["autoscaling"]
        apiVersions: ["v1"]
        operations: ["CREATE", "UPDATE"]
        resources: ["horizontalpodautoscalers"]
      - apiGroups: ["networking.k8s.io"]
        apiVersions: ["v1"]
        operations: ["CREATE", "UPDATE"]
        resources: ["ingresses"]
    namespaceSelector:
      matchExpressions:
        - key: kubernetes.io/metadata.name
          operator: NotIn
          values:
          {{- range (include "pacQuota.excludedNamespacesList" . | splitList " ") }}
          - {{ . | quote }}
          {{- end }}
{{- end }}
