{{- if .Values.webhook.enabled }}
# This file deploys the ValidatingWebhookConfiguration for ClusterResourceQuota
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: pac-quota-controller-validating-webhook
  labels:
    app.kubernetes.io/name: pac-quota-controller
  annotations:
    cert-manager.io/inject-ca-from: {{ .Release.Namespace }}/webhook-server-cert
webhooks:
  - name: vclusterresourcequota-v1alpha1.kb.io
    admissionReviewVersions: ["v1"]
    sideEffects: None
    failurePolicy: Fail
    clientConfig:
      service:
        name: pac-quota-controller-webhook-service
        namespace: {{ .Release.Namespace }}
        path: /validate-quota-powerapp-cloud-v1alpha1-clusterresourcequota
    rules:
      - apiGroups: ["quota.powerapp.cloud"]
        apiVersions: ["v1alpha1"]
        operations: ["CREATE", "UPDATE"]
        resources: ["clusterresourcequotas"]
    namespaceSelector: {}
{{- end }}
