{{- if .Values.webhook.enable }}
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: pac-quota-controller-validating-webhook
  labels:
    app.kubernetes.io/name: pac-quota-controller
  annotations:
    {{- if .Values.certmanager.enable }}
    cert-manager.io/inject-ca-from: {{ .Release.Namespace }}/webhook-server-cert
    {{- end }}
webhooks:
  - name: vclusterresourcequota-v1alpha1.powerapp.cloud
    admissionReviewVersions: ["v1"]
    sideEffects: None
    failurePolicy: Fail
    clientConfig:
      {{- if not .Values.certmanager.enable }}
      caBundle: {{ .Values.webhook.customTLS.caBundle }}
      {{- end }}
      service:
        name: pac-quota-controller-webhook-service
        namespace: {{ .Release.Namespace }}
        path: /validate-quota-powerapp-cloud-v1alpha1-clusterresourcequota
    rules:
      - apiGroups: ["quota.powerapp.cloud"]
        apiVersions: ["v1alpha1"]
        operations: ["CREATE", "UPDATE"]
        resources: ["clusterresourcequotas"]
    namespaceSelector: {}
  - name: vnamespace-v1alpha1.powerapp.cloud
    admissionReviewVersions: ["v1"]
    sideEffects: None
    failurePolicy: Fail
    clientConfig:
      {{- if not .Values.certmanager.enable }}
      caBundle: {{ .Values.webhook.customTLS.caBundle }}
      {{- end }}
      service:
        name: pac-quota-controller-webhook-service
        namespace: {{ .Release.Namespace }}
        # Super annoying but kubebuilder router creates the path
        # using the group and version, namespace doesn't contain a group
        # so we have to double dashes
        path: /validate--v1-namespace
    rules:
      - apiGroups: [""]
        apiVersions: ["v1"]
        operations: ["CREATE", "UPDATE"]
        resources: ["namespaces"]
    namespaceSelector: {}
  - name: vpod-v1alpha1.powerapp.cloud
    admissionReviewVersions: ["v1"]
    sideEffects: None
    failurePolicy: Fail
    clientConfig:
      {{- if not .Values.certmanager.enable }}
      caBundle: {{ .Values.webhook.customTLS.caBundle }}
      {{- end }}
      service:
        name: pac-quota-controller-webhook-service
        namespace: {{ .Release.Namespace }}
        path: /validate--v1-pod
    rules:
      - apiGroups: [""]
        apiVersions: ["v1"]
        operations: ["CREATE", "UPDATE"]
        resources: ["pods"]
    namespaceSelector: {}
{{- end }}
