// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	mock "github.com/stretchr/testify/mock"
	"k8s.io/api/core/v1"
	"k8s.io/apimachinery/pkg/api/resource"
)

// NewMockPodResourceCalculatorInterface creates a new instance of MockPodResourceCalculatorInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockPodResourceCalculatorInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockPodResourceCalculatorInterface {
	mock := &MockPodResourceCalculatorInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockPodResourceCalculatorInterface is an autogenerated mock type for the PodResourceCalculatorInterface type
type MockPodResourceCalculatorInterface struct {
	mock.Mock
}

type MockPodResourceCalculatorInterface_Expecter struct {
	mock *mock.Mock
}

func (_m *MockPodResourceCalculatorInterface) EXPECT() *MockPodResourceCalculatorInterface_Expecter {
	return &MockPodResourceCalculatorInterface_Expecter{mock: &_m.Mock}
}

// CalculatePodCount provides a mock function for the type MockPodResourceCalculatorInterface
func (_mock *MockPodResourceCalculatorInterface) CalculatePodCount(ctx context.Context, namespace string) (int64, error) {
	ret := _mock.Called(ctx, namespace)

	if len(ret) == 0 {
		panic("no return value specified for CalculatePodCount")
	}

	var r0 int64
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (int64, error)); ok {
		return returnFunc(ctx, namespace)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) int64); ok {
		r0 = returnFunc(ctx, namespace)
	} else {
		r0 = ret.Get(0).(int64)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, namespace)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockPodResourceCalculatorInterface_CalculatePodCount_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CalculatePodCount'
type MockPodResourceCalculatorInterface_CalculatePodCount_Call struct {
	*mock.Call
}

// CalculatePodCount is a helper method to define mock.On call
//   - ctx context.Context
//   - namespace string
func (_e *MockPodResourceCalculatorInterface_Expecter) CalculatePodCount(ctx interface{}, namespace interface{}) *MockPodResourceCalculatorInterface_CalculatePodCount_Call {
	return &MockPodResourceCalculatorInterface_CalculatePodCount_Call{Call: _e.mock.On("CalculatePodCount", ctx, namespace)}
}

func (_c *MockPodResourceCalculatorInterface_CalculatePodCount_Call) Run(run func(ctx context.Context, namespace string)) *MockPodResourceCalculatorInterface_CalculatePodCount_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockPodResourceCalculatorInterface_CalculatePodCount_Call) Return(n int64, err error) *MockPodResourceCalculatorInterface_CalculatePodCount_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *MockPodResourceCalculatorInterface_CalculatePodCount_Call) RunAndReturn(run func(ctx context.Context, namespace string) (int64, error)) *MockPodResourceCalculatorInterface_CalculatePodCount_Call {
	_c.Call.Return(run)
	return _c
}

// CalculateTotalUsage provides a mock function for the type MockPodResourceCalculatorInterface
func (_mock *MockPodResourceCalculatorInterface) CalculateTotalUsage(ctx context.Context, namespace string) (map[v1.ResourceName]resource.Quantity, error) {
	ret := _mock.Called(ctx, namespace)

	if len(ret) == 0 {
		panic("no return value specified for CalculateTotalUsage")
	}

	var r0 map[v1.ResourceName]resource.Quantity
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (map[v1.ResourceName]resource.Quantity, error)); ok {
		return returnFunc(ctx, namespace)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) map[v1.ResourceName]resource.Quantity); ok {
		r0 = returnFunc(ctx, namespace)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[v1.ResourceName]resource.Quantity)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, namespace)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockPodResourceCalculatorInterface_CalculateTotalUsage_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CalculateTotalUsage'
type MockPodResourceCalculatorInterface_CalculateTotalUsage_Call struct {
	*mock.Call
}

// CalculateTotalUsage is a helper method to define mock.On call
//   - ctx context.Context
//   - namespace string
func (_e *MockPodResourceCalculatorInterface_Expecter) CalculateTotalUsage(ctx interface{}, namespace interface{}) *MockPodResourceCalculatorInterface_CalculateTotalUsage_Call {
	return &MockPodResourceCalculatorInterface_CalculateTotalUsage_Call{Call: _e.mock.On("CalculateTotalUsage", ctx, namespace)}
}

func (_c *MockPodResourceCalculatorInterface_CalculateTotalUsage_Call) Run(run func(ctx context.Context, namespace string)) *MockPodResourceCalculatorInterface_CalculateTotalUsage_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockPodResourceCalculatorInterface_CalculateTotalUsage_Call) Return(resourceNameToQuantity map[v1.ResourceName]resource.Quantity, err error) *MockPodResourceCalculatorInterface_CalculateTotalUsage_Call {
	_c.Call.Return(resourceNameToQuantity, err)
	return _c
}

func (_c *MockPodResourceCalculatorInterface_CalculateTotalUsage_Call) RunAndReturn(run func(ctx context.Context, namespace string) (map[v1.ResourceName]resource.Quantity, error)) *MockPodResourceCalculatorInterface_CalculateTotalUsage_Call {
	_c.Call.Return(run)
	return _c
}

// CalculateUsage provides a mock function for the type MockPodResourceCalculatorInterface
func (_mock *MockPodResourceCalculatorInterface) CalculateUsage(ctx context.Context, namespace string, resourceName v1.ResourceName) (resource.Quantity, error) {
	ret := _mock.Called(ctx, namespace, resourceName)

	if len(ret) == 0 {
		panic("no return value specified for CalculateUsage")
	}

	var r0 resource.Quantity
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, v1.ResourceName) (resource.Quantity, error)); ok {
		return returnFunc(ctx, namespace, resourceName)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, v1.ResourceName) resource.Quantity); ok {
		r0 = returnFunc(ctx, namespace, resourceName)
	} else {
		r0 = ret.Get(0).(resource.Quantity)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, v1.ResourceName) error); ok {
		r1 = returnFunc(ctx, namespace, resourceName)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockPodResourceCalculatorInterface_CalculateUsage_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CalculateUsage'
type MockPodResourceCalculatorInterface_CalculateUsage_Call struct {
	*mock.Call
}

// CalculateUsage is a helper method to define mock.On call
//   - ctx context.Context
//   - namespace string
//   - resourceName v1.ResourceName
func (_e *MockPodResourceCalculatorInterface_Expecter) CalculateUsage(ctx interface{}, namespace interface{}, resourceName interface{}) *MockPodResourceCalculatorInterface_CalculateUsage_Call {
	return &MockPodResourceCalculatorInterface_CalculateUsage_Call{Call: _e.mock.On("CalculateUsage", ctx, namespace, resourceName)}
}

func (_c *MockPodResourceCalculatorInterface_CalculateUsage_Call) Run(run func(ctx context.Context, namespace string, resourceName v1.ResourceName)) *MockPodResourceCalculatorInterface_CalculateUsage_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 v1.ResourceName
		if args[2] != nil {
			arg2 = args[2].(v1.ResourceName)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockPodResourceCalculatorInterface_CalculateUsage_Call) Return(quantity resource.Quantity, err error) *MockPodResourceCalculatorInterface_CalculateUsage_Call {
	_c.Call.Return(quantity, err)
	return _c
}

func (_c *MockPodResourceCalculatorInterface_CalculateUsage_Call) RunAndReturn(run func(ctx context.Context, namespace string, resourceName v1.ResourceName) (resource.Quantity, error)) *MockPodResourceCalculatorInterface_CalculateUsage_Call {
	_c.Call.Return(run)
	return _c
}
