{{- if .Values.metrics.enable }}
{{- if .Values.certmanager.enable }}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  labels:
    {{- include "chart.labels" . | nindent 4 }}
  name: metrics-certs
  namespace: {{ .Release.Namespace }}
spec:
  dnsNames:
    - pac-quota-controller.{{ .Release.Namespace }}.svc
    - pac-quota-controller.{{ .Release.Namespace }}.svc.cluster.local
    - pac-quota-controller-metrics-service.{{ .Release.Namespace }}.svc
  issuerRef:
    kind: Issuer
    name: selfsigned-issuer
  secretName: metrics-server-cert
{{- end }}
{{- end }}
