apiVersion: v1
kind: Service
metadata:
  name: pac-quota-controller-metrics-service
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "chart.labels" . | nindent 4 }}
    control-plane: controller-manager
spec:
  ports:
    - port: {{ .Values.metrics.port }}
      targetPort: {{ .Values.metrics.port }}
      protocol: TCP
      name: https
  selector:
    control-plane: controller-manager
