name: Helm Chart Release

on:
  push:
    tags:
      - 'chart-v*'

jobs:
  helm:
    permissions:
      contents: read
      packages: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5

      - name: Install Helm
        uses: azure/setup-helm@1a275c3b69536ee54be43f2070a358922e12c8d4 # v4

      - name: Get version from tag
        id: version
        run: |
          VERSION=${GITHUB_REF#refs/tags/chart-v}
          echo "version=${VERSION}" >> $GITHUB_OUTPUT

      - name: Login to GitHub Container Registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | helm registry login ghcr.io --username ${{ github.actor }} --password-stdin

      - name: Package and push chart
        run: |
          helm package charts/pac-quota-controller
          helm push pac-quota-controller-${{ steps.version.outputs.version }}.tgz oci://ghcr.io/powerhome/pac-quota-controller/charts
