name: E2E Tests

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  e2e:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    env:
      KIND_CLUSTER: pac-quota-controller-test-e2e
      IMG: ghcr.io/powerhome/pac-quota-controller:e2e
    steps:
      - name: Checkout code
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5

      - name: Set up Go
        uses: actions/setup-go@d35c59abb061a4a6fb18e82ac0862c26744d6ab5 # v5
        with:
          go-version: '1.24.5'

      - name: Set up Kind
        uses: helm/kind-action@a1b0e391336a6ee6713a0583f8c6240d70863de3 # v1.12.0
        with:
          cluster_name: ${{ env.KIND_CLUSTER }}
          wait: 60s # Add wait for Kind cluster to be ready

      - name: Install kubectl
        run: |
          curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
          chmod +x kubectl
          sudo mv kubectl /usr/local/bin/

      - name: Run e2e tests
        run: |
          make test-e2e

      - name: Dump logs on failure
        if: failure()
        run: |
          echo "Dumping cluster state after potential e2e test failure..."
          kubectl get all -n pac-quota-controller-system
          kubectl describe pods -n pac-quota-controller-system
          kubectl logs -l control-plane=controller-manager -n pac-quota-controller-system --tail=100 || true
          echo "Dumping cert-manager state..."
          kubectl get all -n cert-manager
          kubectl describe pods -n cert-manager
          kubectl logs -l app=cert-manager -n cert-manager --tail=100 || true
          kubectl logs -l app.kubernetes.io/instance=cert-manager -n cert-manager --tail=100 || true
          echo "Describing CRDs..."
          kubectl get crds
          kubectl describe crd clusterresourcequotas.quota.powerapp.cloud
          echo "Describing MutatingWebhookConfigurations..."
          kubectl get mutatingwebhookconfigurations -oyaml
          echo "Describing ValidatingWebhookConfigurations..."
          kubectl get validatingwebhookconfigurations -oyaml
