name: Helm Chart

on:
  push:
    branches:
      - main
    tags:
      - 'v*'
    paths:
      - 'charts/**'
      - 'config/**'
      - 'api/**'
      - 'controllers/**'
      - '.github/workflows/helm-chart.yml'
      - 'Makefile'
  pull_request:
    paths:
      - 'charts/**'
      - 'config/**'
      - 'api/**'
      - 'controllers/**'
      - '.github/workflows/helm-chart.yml'
      - 'Makefile'
  workflow_dispatch:

env:
  CHART_RELEASER_VERSION: 1.6.1

jobs:
  lint-test:
    name: Lint and Test Chart
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Kubebuilder
        run: |
          # Install Kubebuilder v4.6.0
          KB_VERSION="4.6.0"
          
          # Download Kubebuilder release
          curl -L -o kubebuilder "https://github.com/kubernetes-sigs/kubebuilder/releases/download/v${KB_VERSION}/kubebuilder_${os}_${arch}"
          
          # Make it executable and move to path
          chmod +x kubebuilder
          sudo mv kubebuilder /usr/local/bin/
          
          # Verify installation
          kubebuilder version || echo "Kubebuilder installation failed"

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod

      - name: Set up Helm
        uses: azure/setup-helm@v3
        with:
          version: v3.12.1

      - name: Install Helm plugins
        run: |
          helm plugin install https://github.com/helm/chart-testing-plugin || true
          helm plugin install https://github.com/helm/chart-releaser-plugin || true

      - name: Set up chart-releaser
        run: |
          curl -LO "https://github.com/helm/chart-releaser/releases/download/v${CHART_RELEASER_VERSION}/chart-releaser_${CHART_RELEASER_VERSION}_linux_amd64.tar.gz"
          tar -xzf chart-releaser_${CHART_RELEASER_VERSION}_linux_amd64.tar.gz cr
          chmod +x cr
          sudo mv cr /usr/local/bin/

      - name: Set up chart-testing
        uses: helm/chart-testing-action@v2.6.1

      - name: Install helm-docs
        run: |
          HELM_DOCS_VERSION="1.11.0"
          curl -LO "https://github.com/norwoodj/helm-docs/releases/download/v${HELM_DOCS_VERSION}/helm-docs_${HELM_DOCS_VERSION}_Linux_x86_64.tar.gz"
          tar -zxvf helm-docs_${HELM_DOCS_VERSION}_Linux_x86_64.tar.gz
          chmod +x helm-docs
          sudo mv helm-docs /usr/local/bin/
      
      - name: Generate Helm chart
        run: make generate-helm

      - name: Generate Helm docs
        run: make helm-docs
        
      - name: Run chart-testing (lint)
        run: helm lint charts/pac-quota-controller

      - name: Create kind cluster
        uses: helm/kind-action@v1.8.0
        if: github.event_name != 'pull_request'

      - name: Install chart
        if: github.event_name != 'pull_request'
        run: make helm-test

  release:
    name: Release Chart
    runs-on: ubuntu-latest
    needs: lint-test
    if: github.event_name == 'push' && contains(github.ref, 'refs/tags/v')
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Set up Helm
        uses: azure/setup-helm@v3
        with:
          version: v3.12.1

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod

      - name: Set up Kubebuilder
        run: |
          # Install Kubebuilder v4.6.0
          os=$(go env GOOS)
          arch=$(go env GOARCH)
          KB_VERSION="4.6.0"
          
          # Download Kubebuilder release
          curl -L -o kubebuilder "https://github.com/kubernetes-sigs/kubebuilder/releases/download/v${KB_VERSION}/kubebuilder_${os}_${arch}"
          
          # Make it executable and move to path
          chmod +x kubebuilder
          sudo mv kubebuilder /usr/local/bin/
          
          # Verify installation
          kubebuilder version || echo "Kubebuilder installation failed"

      - name: Set up chart-releaser
        run: |
          curl -LO "https://github.com/helm/chart-releaser/releases/download/v${CHART_RELEASER_VERSION}/chart-releaser_${CHART_RELEASER_VERSION}_linux_amd64.tar.gz"
          tar -xzf chart-releaser_${CHART_RELEASER_VERSION}_linux_amd64.tar.gz cr
          chmod +x cr
          sudo mv cr /usr/local/bin/

      - name: Install helm-docs
        run: |
          HELM_DOCS_VERSION="1.11.0"
          curl -LO "https://github.com/norwoodj/helm-docs/releases/download/v${HELM_DOCS_VERSION}/helm-docs_${HELM_DOCS_VERSION}_Linux_x86_64.tar.gz"
          tar -zxvf helm-docs_${HELM_DOCS_VERSION}_Linux_x86_64.tar.gz
          chmod +x helm-docs
          sudo mv helm-docs /usr/local/bin/

      - name: Generate Helm chart
        run: make generate-helm

      - name: Update version in Chart.yaml
        run: |
          TAG=${GITHUB_REF#refs/tags/v}
          sed -i "s/version:.*/version: ${TAG}/" charts/pac-quota-controller/Chart.yaml
          sed -i "s/appVersion:.*/appVersion: \"${TAG}\"/" charts/pac-quota-controller/Chart.yaml
          cat charts/pac-quota-controller/Chart.yaml

      - name: Generate Helm docs
        run: make helm-docs

      - name: Package chart
        run: |
          mkdir -p .cr-release-packages
          helm package charts/pac-quota-controller --destination .cr-release-packages

      - name: Upload chart to GitHub Pages
        run: |
          cr upload \
            --owner powerhome \
            --git-repo pac-quota-controller \
            --release-name-template "{{ .Version }}" \
            --package-path .cr-release-packages \
            --token ${{ secrets.GITHUB_TOKEN }}

      - name: Index charts
        run: |
          cr index \
            --owner powerhome \
            --git-repo pac-quota-controller \
            --pages-branch gh-pages \
            --push \
            --token ${{ secrets.GITHUB_TOKEN }}

      - name: Verify Helm repository
        run: |
          helm repo add powerhome https://powerhome.github.io/pac-quota-controller
          helm repo update
          helm search repo powerhome/pac-quota-controller
