name: Helm Chart Release

on:
  push:
    tags:
      - 'chart-v*'

jobs:
  helm-gh-pages:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Publish Helm chart to GitHub Pages
        uses: stefanprodan/helm-gh-pages@master
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
