name: Pre-commit Checks

on:
  pull_request:
    paths:
      - '**.go'
      - 'Makefile'
      - '.pre-commit-config.yaml'
      - 'ct.yaml'
      - '**.md'
      - '**.yaml'
      - '**.yml'

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      - name: Set up Go
        uses: actions/setup-go@d35c59abb061a4a6fb18e82ac0862c26744d6ab5 # v5
        with:
          go-version: '1.24.5'
          check-latest: true
      - name: Install dependencies
        run: make deps
      - name: Run fmt
        run: make fmt
      - name: Run vet
        run: make vet
      - name: Run make generate
        run: make generate
      - name: Run make helm-docs
        run: make helm-docs
      - name: Check for uncommitted changes (codegen, manifests, lint)
        run: |
          git diff --exit-code || (echo 'ERROR: Uncommitted changes after codegen/lint. Please run make manifests, make generate, make lint and commit the results.' && exit 1)
